#!/usr/bin/env bash

set -ex

if [[ -d deploy ]]; then
  rm -rf deploy
fi

mkdir deploy
cp -r $(nix-build)/* deploy
chmod u+rwx -R deploy
netlify deploy --prod

# This is needed because I turn off automatic publishing.

echo "Fetching last deploy..."
deploy_id=$(curl -s -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys | jq -r '.[0].id')
echo "Found $deploy_id"
curl -s -X POST -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys/$deploy_id/restore
echo "Made $deploy_id active"
